"""empty message

Revision ID: 163701c29dcf
Revises: 8da9e964112c
Create Date: 2023-08-18 11:47:43.713691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163701c29dcf'
down_revision = '8da9e964112c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
