"""empty message

Revision ID: 1d9a51a3fdc5
Revises: 3d74f3dd4210
Create Date: 2023-09-11 04:15:54.784612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9a51a3fdc5'
down_revision = '3d74f3dd4210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_no', sa.Integer(), nullable=False))
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('invoice_no')

    # ### end Alembic commands ###
