"""empty message

Revision ID: 7175d8cb9981
Revises: d2270b19fd6e
Create Date: 2023-09-15 09:07:01.545383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7175d8cb9981'
down_revision = 'd2270b19fd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint('fk_invoice_client', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_client_id', 'client', ['client_id'], ['id'])
        batch_op.drop_column('client')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_invoice_client_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_client', 'client', ['client'], ['id'])
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
