"""empty message

Revision ID: 90070c39d06d
Revises: 9a32bdc6222a
Create Date: 2023-08-18 11:00:31.778454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90070c39d06d'
down_revision = '9a32bdc6222a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
